extends:
- airbnb-base
- airbnb-typescript/base

parserOptions:
  project: ./tsconfig.eslint.json

env:
  browser: true
  node: true

rules:
  arrow-parens: 0
  no-underscore-dangle: 0
  no-param-reassign: 0
  max-len: [1, 120]
  'import/no-named-as-default': 0
  '@typescript-eslint/type-annotation-spacing': 2
